<?php namespace ProcessWire;

use Purl\Url;

/**
 * AlertData
 *
 * Class for Storing Data to create Twig Alerts
 *
 * @property string type    Bootstrap alert-* class info|success|warning|danger
 * @property string title   Alert Title
 * @property string icon    Icon Class to use (font-awesome)
 * @property string message Message to display in body
 */
class AlertData extends WireData implements Module {
	public function __construct() {
		$this->type    = 'info';
		$this->title   = '';
		$this->icon    = '';
		$this->message = '';
	}

	public static function newDanger($title = '', $message = '') {
		$alert = new AlertData();
		$alert->type = 'danger';
		$alert->icon = 'fa fa-warning fa-2x';
		$alert->title = $title;
		$alert->message = $message;
		return $alert;
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus AlertData',
			'version' => 101,
			'summary' => 'Module for Storing Data to create Twig Alerts',
			'singular' => false,
			'autoload' => true,
		);
	}
}
