<?php namespace ProcessWire;

/**
 * Module for Searching Item Pages
 * @property User   $user         User
 * @property string $selector     Selector String
 * @property string $q            Search Query
 * @property bool   $onlystocked  Search only items with available stock? default = true
 */
class ItemSearch extends WireData implements Module {
	// Processwire Selectors
	// https://processwire.com/api/selectors/
	const SELECTOR_TEMPLATE = 'template=item';
	const SELECTOR_SEARCH = 'title|body|itemid|name|description1';

	public function __construct() {
		$this->selector = self::SELECTOR_TEMPLATE;
		$this->q = '';
		$this->onlystocked = true;
		$this->sortby = 'itemid';
		$this->sortrule = 'asc';
		$this->restrictitems = true;
	}

	public function send_request_all() {
		$this->_send_request_all();
	}

	public function _send_request_all() {
		$dpluspricing = $this->wire('modules')->get('ItemSearchDplus');
		if ($dpluspricing->pricing_needs_update()) {
			$dpluspricing->request_all();
			sleep(2);
		}
	}

	/**
	 * Set User
	 * @param User
	 */
	public function set_user($user) {
		$this->user = $user;
	}

	/**
	 * Set Search string
	 * @param string $q
	 */
	public function set_search($q) {
		$this->q = $q;
	}

	/**
	 * Set SortBy
	 * @param string $sortby   Field to Sort By
	 * @param string $sortrule asc|desc
	 */
	public function set_sort($sortby, $sortrule) {
		$sortrule = strtolower($sortrule);
		$this->sortby  = $sortby;
		$this->sortrule = in_array($sortrule, array('asc', 'desc')) ? $sortrule : 'asc';
	}

	/**
	 * Set if Searching only Items that have available stock
	 * @param bool $onlystocked
	 */
	public function set_onlystocked($onlystocked = true) {
		$this->onlystocked = true;
	}

	/**
	 * Return PW sort rule
	 * @return string
	 */
	public function pw_sortrule() {
		$sortrule = strtolower($this->sortrule) == 'desc' ? '-' : '';
		return $this->sortby . $sortrule;
	}

	/**
	 * Return the number of Item Pages that match selector
	 * @return int
	 */
	public function count() {
		$selector = $this->get_q_selector();
		$this->selector = $selector;
		$count = $this->wire('pages')->count($selector);
		return $this->onlystocked ? $this->count_stocked($selector) : $count;
	}

	/**
	 * Return the Number of Item Pages that match selector and have stock
	 * @param  string $selector
	 * @return int
	 */
	public function count_stocked($selector) {
		$inventory = $this->wire('modules')->get('ItemSearchDplus');
		$items = $this->wire('pages')->find($selector);
		$itemIDs = $items->explode('itemid');
		return $inventory->count_pricing_itemids_stocked($itemIDs);
	}

	/**
	 * Return Pages(template=item) that match Selector
	 * @param  int    $pagenbr  What Page number to start on
	 * @param  int    $limit    Number of Pages to return
	 * @return PageArray
	 */
	public function find($pagenbr = 1, $limit = 10) {
		$start = $pagenbr > 1 ? ($pagenbr * $limit) - $limit : 0;
		$selector = $this->get_q_selector();
		$items = $this->wire('pages')->find($selector);

		$items = $this->onlystocked ? $this->find_stocked($items) : $items;

		if ($limit) {
			$selector = "limit=$limit, start=$start";
		}
		$selector .= ", sort=" . $this->pw_sortrule();
		$this->selector = $selector;
		$results = $items->find($selector);
		return $items->find($selector);
	}

	/**
	 * Return Pages(template=item) that match Selector, and that are stocked
	 * @param  int    $pagenbr  What Page number to start on
	 * @param  int    $limit    Number of Pages to return
	 * @return PageArray
	 */
	public function find_stocked(PageArray $items) {
		$inventory = $this->wire('modules')->get('ItemSearchDplus');
		$itemIDs = $items->explode('itemid');
		$itemIDs_stocked = $inventory->get_pricing_itemids_stocked($itemIDs);
		return $items->find('itemid='.implode('|', $itemIDs_stocked));
	}

	/**
	 * Return Selector for searching
	 * @return string
	 */
	public function get_q_selector() {
		$replace = ['-' => '', '–' => ''];
		$q = str_replace('–', '', $this->q);
		$sanitizer = $this->wire('sanitizer');
		$selector = self::SELECTOR_TEMPLATE;
		$searchFields = self::SELECTOR_SEARCH;
		$selector .= $this->restrictitems ? $this->get_restricted_items_selector() : '';
		$selector .= $this->q ? ", ($searchFields%=$q)" : '';
		$selector .= $this->q ? ", ($searchFields~=$q)" : '';
		return $selector;
	}

	/**
	 * Return Selector for Restricted Items for User
	 * @return string
	 */
	public function get_restricted_items_selector() {
		$user = $this->user;
		$pages = $this->wire('pages');

		if ($user->has_item_restrictions()) {
			$groups = implode('|', $user->restricted_itemgroups());
			$ids    = implode('|', $pages->find("template=item-group,groupcode=$groups")->explode('id'));
			return ",parent=$ids";
		}
		return '';
	}


/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Search Items Module',
			'version' => 101,
			'summary' => 'Handles Item Searching',
			'singular' => true,
			'autoload' => true,
		);
	}

	public function init() {
		//$this->send_request_all();
		$this->user = $this->wire('user');
	}
}
