<?php namespace ProcessWire;

use Propel\Runtime\ActiveQuery\Criteria;

use PricingQuery, Pricing;

/**
 * Module for Searching Item Pages
 */
class ItemSearchDplus extends WireData implements Module {

	const UPDATE_EVERY = '5 minutes';

	public function pricing_needs_update() {
		$q = PricingQuery::create();
		$q->select('time');
		$q->filterBySessionid($this->sessionID);
		$q->filterByDate(date('Ymd'));
		if ($q->count() === false) {
			return true;
		}
		$time = $q->findOne();
		$datetime = (date('Ymd').substr($time, 0, 4));
		return strtotime($datetime) < strtotime('-' . self::UPDATE_EVERY);
	}


	/**
	 * Return Pricing Record
	 * @param  string $itemID Item ID
	 * @return Pricing
	 */
	public function get_pricing_item($itemID) {
		$q = PricingQuery::create();
		$q->filterBySessionid($this->sessionID);
		$q->filterByItemid($itemID);
		return $q->findOne();
	}

	/**
	 * Return Pricing Records for these item IDs
	 * @param  array  $itemIDs item IDs
	 * @return Pricing[]|ObjectCollection
	 */
	public function get_pricing_itemids_stocked(array $itemIDs = []) {
		$q = PricingQuery::create();
		$q->select('itemid');
		$q->filterBySessionid($this->sessionID);

		if (!empty($itemIDs)) {
			$q->filterByItemid($itemIDs);
		}

		$q->filterByQty(0, Criteria::GREATER_THAN);
		return $q->find()->toArray();
	}

	/**
	 * Return Pricing Records for these item IDs
	 * @param  array  $itemIDs item IDs
	 * @return Pricing[]|ObjectCollection
	 */
	public function count_pricing_itemids_stocked(array $itemIDs) {
		$q = PricingQuery::create();
		$q->filterBySessionid($this->sessionID);
		$q->filterByItemid($itemIDs);
		$q->filterByQty(0, Criteria::GREATER_THAN);
		return $q->count();
	}

	/**
	 * Request Pricing Record for Item
	 * @param  string $itemID Item ID
	 * @return void
	 */
	public function request_one($itemID) {
		$this->request_multi(array($itemID));
	}

	/**
	 * Request Pricing Record for Items
	 * @param  array  $itemIDs Item IDs
	 * @return void
	 */
	public function request_multi(array $itemIDs) {
		$data = $this->create_search_data($itemIDs);
		$requestor = $this->wire('modules')->get('DplusRequest');
		$requestor->write_dplusfile($data, $this->sessionID);
		$requestor->cgi_request($this->wire('config')->cgis['default'], $this->sessionID);
	}

	/**
	 * Request Pricing Record for Items
	 * @param  array  $itemIDs Item IDs
	 * @return void
	 */
	public function request_all() {
		$itemIDs = $this->wire('modules')->get('UgmOrderingPagesItem')->get_active_itemids();
		$data = $this->create_search_data($itemIDs);
		$requestor = $this->wire('modules')->get('DplusRequest');
		$requestor->write_dplusfile($data, $this->sessionID);
		$requestor->cgi_request($this->wire('config')->cgis['default'], $this->sessionID);
	}

	/**
	 * Return Data array necessary to request Item Pricing Records
	 * @param  array  $itemIDs Item IDs
	 * @return array
	 */
	protected function create_search_data(array $itemIDs) {
		$dplusdb = $this->wire('modules')->get('DplusDatabaseDpluso')->db_name;
		$data = array("DBNAME=$dplusdb", 'ITMPRIMULT');
		foreach ($itemIDs as $itemID) {
			$data[] = "ITEMID=$itemID";
		}
		return $data;
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public function init() {
		$this->sessionID = 'riccrmebu2ethtcns89fdg1962';

		$this->addHook('Page(template=item-group)::get_stocked_items', function($event) {
			$p = $event->object;
			$itemIDs_stocked = $this->get_pricing_itemids_stocked();
			$event->return = $p->children()->find('itemid='.implode('|', $itemIDs_stocked).',sort=itemid');
		});
	}

	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Search Items Module',
			'version' => 101,
			'summary' => 'Handles Item Searching',
			'singular' => true,
			'autoload' => true,
		);
	}
}
