<?php namespace ProcessWire;

use Propel\Runtime\ActiveQuery\Criteria;

use SalesOrderQuery, SalesOrder;
use SalesHistoryQuery, SalesHistory;

/**
 * Lookup Sales Orders
 *
 * Class for Looking up / Validating Sales Orders
 *
 * @property string $exists  Sales Order / Invoice Exists
 * @property string $ordn    Sales Order / Invoice Number
 * @property string $request What was sent to find Sales Order / Invoice Number
 * @property string $source  so_head | so_head_hist
 */
class ValidateOrder extends WireData implements Module {
	public function __construct() {
		$this->exists  = false;
		$this->ordn  = '';
	}

	/**
	 * Returns if Order # exists in the Sales Order table
	 * @param  string $ordn Order #
	 * @return bool
	 */
	public function order($ordn) {
		$q = SalesOrderQuery::create();
		$q->filterByOrdernumber($ordn);

		if ($q->count()) {
			$this->exists = true;
			$this->ordn = $ordn;
		} else {
			$this->exists = false;
		}
		return $this->exists;
	}

	/**
	 * Returns if User can view order according to their custid
	 * @param  string $ordn Order #
	 * @param  User   $user User
	 * @return bool
	 */
	public function order_user($ordn, User $user) {
		$q = SalesOrderQuery::create();
		$q->filterByOrdernumber($ordn);
		$q->filterByCustid($user->custid);
		return boolval($q->count());
	}



	/**
	 * Returns if Order # exists in the Sales History table
	 * @param  string $ordn Order #
	 * @return bool
	 */
	public function invoice($ordn) {
		$q = SalesHistoryQuery::create();
		$q->filterByOrdernumber($ordn);

		if ($q->count()) {
			$this->exists = true;
			$this->ordn = $ordn;
		} else {
			$this->exists = false;
		}
		return $this->exists;
	}

	/**
	 * Returns if User can view order according to their custid
	 * @param  string $ordn Order #
	 * @param  User   $user User
	 * @return bool
	 */
	public function invoice_user($ordn, User $user) {
		$q = SalesHistoryQuery::create();
		$q->filterByOrdernumber($ordn);
		$q->filterByCustid($user->custid);

		return boolval($q->count());
	}

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Sales Order Validate Module',
			'version' => 101,
			'summary' => 'Handles Order # Validation',
			'singular' => true,
			'autoload' => true,
			'installs' => array()
		);
	}
}
