<?php namespace ProcessWire;

use Propel\Runtime\ServiceContainer\ServiceContainerInterface;

/**
 * DplusDatabaseDpluso
 *
 * Class for Creating Connection to the dpluso(x) databases for Dplus
 * NOTE these are the Session based database so the data is only live for the session and last refresh
 */
class DplusDatabaseDpluso extends DplusDatabase implements ConfigurableModule {
	const CONNECTION_NAME_PROPEL = 'dplusodb';
	const CONNECTION_NAME_PW = 'dpluso';

	/**
	 * Returns Config to connect to Database
	 * @return Config
	 */
	public function get_dbconfig() {
		$config = $this->wire('config');
		$dbconfig = parent::get_dbconfig();

		if (!empty($this->db_name)){
			$this->db_name = $this->db_name;
		} else {
			$this->db_name = !empty($config->dplusdbname) ? $config->dplusdbname : "dpluso$config->COMPANYNBR";
		}
		$dbconfig->dbName = $this->db_name;
		return $dbconfig;
	}

/* =============================================================
	Propel Functions
============================================================= */
	/**
	 * Sets the Default datasource
	 * NOTE we don't want it to do anything when connecting
	 * @param ServiceContainerInterface $serviceContainer
	 */
	protected function set_propel_service_default(ServiceContainerInterface $serviceContainer) {

	}
/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		$infoArray = array(
			'title' => __('Dplus Online Database Connection'),
			'version' => 115,
			'summary' => __("Creates Connection to Dplus Online Database"),
			'autoload' => true,
			'singular' => true,
			'author' => 'pauldro',
			'icon' => 'database',
			'requires' => array('DplusDatabase')
		);
		return $infoArray;
	}
}
